### ISSUE TITLE
Init `token-stake` program

### ISSUE THREAD

**Issue by eliagoris** [vivendell/solana-programs#11]
**User Story**

_Me as a user, I want to be able to stake my tokens so that I can become a loyal holder_
_Me as a user, I want to be able to unstake my tokens, so that I can collect my rewards for the time I hold and retrieve my tokens back_
_Me as a user, I want to be able to collect rewards from my staked tokens, so that I can be compensated for being a holder_

- [ ] Init program
- [ ] Add handler to stake
- [ ] Add handler to unstake
- [ ] Add handler to collect reward

**Comment by lucasig11** [comment]
Should we close this issue and #10?
